// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace BDDLiving.Feature
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("CustomerBuysItem")]
    public partial class CustomerBuysItemFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "CustomerBuysItem.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Feature", "CustomerBuysItem", null, ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Customer buys Guava")]
        public void CustomerBuysGuava()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Customer buys Guava", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 3
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
 testRunner.Given("they are on fruit stall", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 5
 testRunner.And("they select Guava", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 6
 testRunner.When("they paid \"68p\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 7
 testRunner.Then("they able to buy the Guava successfully", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Customer buys fruits on different days")]
        [NUnit.Framework.TestCaseAttribute("Day 1", "Guava", "1", "20", "20", null)]
        [NUnit.Framework.TestCaseAttribute("Following Day", "Guava", "2", "25", "50", null)]
        [NUnit.Framework.TestCaseAttribute("Following Day", "Orange", "1", "35", "35", null)]
        [NUnit.Framework.TestCaseAttribute("Two days later", "Guava", "1", "35", "35", null)]
        [NUnit.Framework.TestCaseAttribute("Two days later", "Orange", "2", "30", "60", null)]
        public void CustomerBuysFruitsOnDifferentDays(string day, string fruitItem, string quantity, string pricePerItem, string total, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("day", day);
            argumentsOfScenario.Add("fruitItem", fruitItem);
            argumentsOfScenario.Add("quantity", quantity);
            argumentsOfScenario.Add("pricePerItem", pricePerItem);
            argumentsOfScenario.Add("total", total);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Customer buys fruits on different days", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 9
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 10
    testRunner.Given("they are on fruit stall", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "fruitItem",
                            "quantity",
                            "pricePerItem"});
                table3.AddRow(new string[] {
                            string.Format("{0}", fruitItem),
                            string.Format("{0}", quantity),
                            string.Format("{0}", pricePerItem)});
#line 11
    testRunner.And(string.Format("the customer buys the following fruits on {0}:", day), ((string)(null)), table3, "And ");
#line hidden
#line 14
    testRunner.When(string.Format("they make {0} payment", total), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 15
    testRunner.Then("they able to buy fruit sucessfully", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("An employee purchases foods using credit card from food court")]
        [NUnit.Framework.TestCaseAttribute("Day 1", "Pizza", "10", "5.5", "50.5", "Transaction is successful", null)]
        [NUnit.Framework.TestCaseAttribute("Day 1", "Popcorn", "6", "1", "6", "Transaction is successful", null)]
        [NUnit.Framework.TestCaseAttribute("Day 2", "Chicken burgers and coke", "8", "6", "48", "Transaction is successful", null)]
        [NUnit.Framework.TestCaseAttribute("Day 3", "Pav Bhaji", "7", "4", "28", "Transaction is unsuccessful", null)]
        public void AnEmployeePurchasesFoodsUsingCreditCardFromFoodCourt(string day, string foodItem, string quantity, string pricePerItem, string total, string status, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("day", day);
            argumentsOfScenario.Add("foodItem", foodItem);
            argumentsOfScenario.Add("quantity", quantity);
            argumentsOfScenario.Add("pricePerItem", pricePerItem);
            argumentsOfScenario.Add("total", total);
            argumentsOfScenario.Add("status", status);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("An employee purchases foods using credit card from food court", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 24
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "foodItem",
                            "quantity",
                            "pricePerItem"});
                table4.AddRow(new string[] {
                            string.Format("{0}", foodItem),
                            string.Format("{0}", quantity),
                            string.Format("{0}", pricePerItem)});
#line 25
    testRunner.Given(string.Format("the employee purchases the following foods on {0}:", day), ((string)(null)), table4, "Given ");
#line hidden
#line 28
    testRunner.When(string.Format("they make {0} payment using credit card", total), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 29
    testRunner.Then(string.Format("they see transaction {0}", status), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Customer buys items from FlipKart and pay through PayTM account")]
        public void CustomerBuysItemsFromFlipKartAndPayThroughPayTMAccount()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Customer buys items from FlipKart and pay through PayTM account", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 37
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 38
    testRunner.Given("the customer have £100.00 in PayTM account", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 39
    testRunner.And("the customer logged in with valid credentials", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "ItemName",
                            "Price"});
                table5.AddRow(new string[] {
                            "Pro Kabbaddi shirt",
                            "£15"});
#line 40
    testRunner.And("they add the below items into cart on day 1:", ((string)(null)), table5, "And ");
#line hidden
#line 43
    testRunner.And("they make payment \"£15\" through PayTM account", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 44
    testRunner.And("the order placed successfully", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 45
 testRunner.And("the balance in PayTM account is \"£85.00\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                            "ItemName",
                            "Price"});
                table6.AddRow(new string[] {
                            "Signed music CD of A R Rehman",
                            "£45"});
                table6.AddRow(new string[] {
                            "Signed music CD of Pritam",
                            "£35"});
#line 46
 testRunner.And("they add the below items into cart on day 2:", ((string)(null)), table6, "And ");
#line hidden
#line 50
    testRunner.And("they make payment \"£80\" through PayTM account", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 51
    testRunner.And("the order placed successfully", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 52
 testRunner.And("the balance in PayTM account is \"£5.00\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                            "ItemName",
                            "Price"});
                table7.AddRow(new string[] {
                            "Bluetooth headphone",
                            "£32"});
#line 53
 testRunner.And("they add the below items into cart on day 3:", ((string)(null)), table7, "And ");
#line hidden
#line 56
    testRunner.And("they make payment \"£32\" through PayTM account", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 57
    testRunner.And("the order is not placed successfully due to insufficient fund", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 58
    testRunner.And("on day four, they add \"£30.00\" into PayTM account wallet", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 59
 testRunner.And("the balance in PayTM account is \"£35.00\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                            "ItemName",
                            "Price"});
                table8.AddRow(new string[] {
                            "Bluetooth headphone",
                            "£32"});
#line 60
    testRunner.And("they add the below items into cart on day 4:", ((string)(null)), table8, "And ");
#line hidden
#line 63
    testRunner.When("they make payment \"£32\" through PayTM account", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 64
    testRunner.Then("the order placed successfully", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 65
 testRunner.And("the balance in PayTM account is \"£3.00\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
